name: Run JUnit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Compile and run tests
      run: |
        javac -cp .:junit-platform-console-standalone-<version>.jar Tests/*.java
        java -jar junit-platform-console-standalone-<version>.jar --class-path . --scan-class-path

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports/tests
