name: Java CI with JUnit

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download JUnit JAR
      run: |
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/x.y.z/junit-platform-console-standalone-x.y.z.jar
        ls -al  # Verify that the JUnit JAR is downloaded

    - name: Compile and run tests
      run: |
        javac -cp .:junit-platform-console-standalone-x.y.z.jar Tests/*.java
        java -jar junit-platform-console-standalone-x.y.z.jar --class-path . --scan-class-path

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports/tests
