name: Java CI with JUnit

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download JUnit JAR
      run: |
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.0/junit-platform-console-standalone-1.7.0.jar

        ls -al  # Verify that the JUnit JAR is downloaded

    - name: Compile and run tests
      run: |
        javac -cp .:junit-platform-console-standalone-1.7.0.jar Tests/*.java
        java -jar junit-platform-console-standalone-1.7.0.jar --class-path . --scan-class-path
